variables:
  TYPE: app

image: golang:1.20

include:
  - project: shared-scripts/gitlab-ci
    file: /autodevops-golang.yml
    ref: v1

Docker Release:
  variables:
    PROJECT_VERSION: "${CI_COMMIT_REF_NAME}"

Deploy Dev Manual:
  rules:
    - when: never

Deploy Fat:
  rules:
    - when: never
