repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=charts
          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl
          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
    - id: helmlint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        name: Run go fmt against the code
