# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: e2e-test
spec:
  timeouts:
    apply: 30s
    assert: 15s
    cleanup: 2m
    delete: 1m
    error: 1m
    exec: 1m
  steps:
    - name: Install thundering-herd-scheduler
      try:
        - description: Install thundering-herd-scheduler
          script:
            timeout: 2m
            content: |
              helm upgrade --install --namespace=kube-system thundering-herd-scheduler ../../charts/thundering-herd-scheduler --wait --timeout 90s --set replicaCount=1 --set image.tag=${IMAGE_TAG}
            env:
              - name: IMAGE_TAG
                value: (env('IMAGE_TAG'))
      cleanup:
        - script:
            timeout: 1m
            content: |
              helm uninstall --namespace=kube-system thundering-herd-scheduler --wait --timeout 45s
    - name: perform test
      try:
        - description: install example workload
          apply:
            file: ../../manifests/development/example.yaml
        - description: wait for deployment to be completed
          wait:
            apiVersion: apps/v1
            kind: Deployment
            timeout: 5m
            for:
              jsonPath:
                path: .status.readyReplicas
                value: "5"
        - description: find if "delay" events present
          script:
            content: |
              kubectl get events -n $NAMESPACE -ojson | jq -r '[.items[] | select(.message == "0/1 nodes are available: 1 rejected due to timeout after waiting 25s at plugin ThunderingHerdScheduling.")] | length > 0'
            env:
              - name: NAMESPACE
                value: ($namespace)
            check:
              (contains($stdout, 'true')): true
  catch:
    - script:
        content: helm list
        timeout: 1m
    - get:
        kind: Pod
        apiVersion: v1
        namespace: kube-system
    - get:
        kind: Pod
        apiVersion: v1
    - get:
        kind: Deployment
        apiVersion: apps/v1
    - events: {}
    - podLogs:
        timeout: 30s
        tail: 200
        selector: app.kubernetes.io/instance=thundering-herd-scheduler
