apiVersion: apps/v1
kind: Deployment
metadata:
  name: thundering-herd-scheduler-training-server
  labels:
    app: thundering-herd-scheduler-training-server
spec:
  replicas: 5
  template:
    metadata:
      name: thundering-herd-scheduler-training-server
      labels:
        app: thundering-herd-scheduler-training-server
    spec:
      schedulerName: thundering-herd-scheduler
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - thundering-herd-scheduler-training-server
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nginx
          image: daspawnw/training-server:latest
          livenessProbe:
            httpGet:
              port: 8080
              path: "/health"
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: "/health"
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: thundering-herd-scheduler-training-server
