on:
  push:
    tags:
      - "v*.*-*"
name: Release
jobs:
  docker-build:
    uses: ./.github/workflows/docker
  build-and-test:
    uses: ./.github/workflows/build
  create-release:
    needs:
      - docker-build
      - build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: thundering-herd-scheduler-binaries
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/thundering-herd-scheduler*
