on:
  push:
    tags:
      - "v*.*-*"
name: Release
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: thundering-herd-scheduler-binaries
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/thundering-herd-scheduler*
